# look up here to change when we will build docs: https://docs.readthedocs.io/en/stable/config-file/v2.html
# Required
version: 2

# Image to use
build:
  image: latest

# Configuration
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
